export const host = ""; // Use relative paths
export const loginRoute = `/api/auth/login`;
export const registerRoute = `/api/auth/register`;
export const logoutRoute = `/api/auth/logout`;
export const sendMessageRoute = `/api/messages/addmsg`;
export const uploadImageRoute = `/api/messages/uploadimg`;
export const recieveMessageRoute = `/api/messages/getmsg`;
export const markAsReadRoute = `/api/messages/markasread`;
export const unsendMessageRoute = `/api/messages/unsendmsg`;
export const removeMessageRoute = `/api/messages/removemsg`;
export const deleteConversationRoute = `/api/messages/delete-conversation`;
export const deleteConversationForMeRoute = `/api/messages/delete-conversation-for-me`;
export const addReactionRoute = `/api/messages/react`;
export const removeReactionRoute = `/api/messages/react`;
export const allUsersRoute = `/api/auth/allusers`;
export const setAvatarRoute = `/api/auth/setavatar`;
export const getAllConversationsRoute = `/api/auth/allconversations`;
export const activeConversationsRoute = `/api/auth/active-conversations`;
